version: '3'

services:

   neo4j:
      
      container_name: neo4j
      restart: always
      build: .
      ports:
         - "7474:7474"
         - "7687:7687"
#      volumes:
#         - neo4j:/var/lib/neo4j/data

#volumes:

#   neo4j:
#      external: true
